apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: example-job-container
        image: busybox
        command: ["sh", "-c", "for i in $(seq 1 15); do echo \"Hello World --> $i\"; sleep 2; done"]
      restartPolicy: Never