apiVersion: v1
kind: Service
metadata:
  name: fastapi-fibonacci-service
spec:
  type: NodePort
  selector:
    app: fastapi-fibonacci
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30370